name: Mirror rolling to master

on:
  push:
    branches: [ rolling ]

jobs:
  mirror-to-master:
    runs-on: ubuntu-latest
    steps:
    - run: echo "$GITHUB_ACTOR"
    - uses: zofrex/mirror-branch@v1
      with:
        target-branch: master
